nailezhuang/milk/urls.py
from django.conf.urls import url
from . import views

app_name="milk"
urlpatterns =[
	url(r'^$', views.index, name='index'),
	url(r'^StasticsReq/', views.StasticsReq, name='StasticsReq'),
	url(r'^StasticsRes/', views.StasticsRes, name='StasticsRes'),
	url(r'^VIPStasticsReq/', views.VIPStasticsReq, name='VIPStasticsReq'),
	url(r'^VIPStasticsRes/', views.VIPStasticsRes, name='VIPStasticsRes'),
]

nailezhuang/nailezhuang/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^milk/', include("milk.urls")),
	url(r'^', admin.site.urls),
]

nailezhuang/milk/models.py
#-*- coding:utf8 -*-

from django.db import models

# Create your models here.
class FoodType(models.Model):
	'''奶乐状物品类型'''
	foodname = models.CharField("物品名称", max_length=100, unique = True)
	foodprice = models.DecimalField("物品售价", max_digits=10, decimal_places=3, default=0)
	
	def __str__(self):
		return self.foodname
		

class FoodRecord(models.Model):
	'''奶乐状物品记录'''
	foodtype = models.ForeignKey(FoodType, on_delete=models.CASCADE)
	foodcnt = models.PositiveIntegerField("数量", default=1)
	foodmoney = models.DecimalField("金额", max_digits=30, decimal_places=3)
	foodtime = models.DateTimeField("时间")
	
	def __str__(self):
		return str(self.id)
	

class VIPType(models.Model):
	'''奶乐状月卡类型'''
	viptype = models.CharField("月卡类型名称", max_length=30, unique = True)
	
	def __str__(self):
		return self.viptype	
		

class VIPInfo(models.Model):
	'''奶乐状月卡用户信息'''
	vipindex = models.CharField("用户编号", max_length=20, unique = True)
	vipname = models.CharField("用户名", max_length=30)
	vipnumber = models.CharField("用户电话", max_length=15)
	viptype = models.ForeignKey(VIPType, on_delete=models.CASCADE)
	vipcnt = models.PositiveIntegerField("月卡牛奶数量", default=32)
	
	def __str__(self):
		return self.vipindex	
		
	
class VIPRecord(models.Model):
	'''奶乐状月卡使用记录'''
	viprecordname = models.ForeignKey(VIPInfo, on_delete=models.CASCADE)
	viprecordcnt = models.PositiveIntegerField("数量", default=1)
	viprecordtime = models.DateTimeField("时间")
	
	def __str__(self):
		return str(self.id)
		
	
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

	
	
	
	

nailezhuang/milk/views.py
# -*- coding: utf8 -*- 
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.contrib import auth
from . import MilkCommon

@login_required
def index(request):
	href_dict = {}
	url_str = "http://127.0.0.1:8009/milk/%s/"
	for value in globals().items():
		if type(value[1])!=type(MilkCommon._f):
			continue
		fobj = globals()[value[0]]
		doc = fobj.__doc__
		if doc is None or doc.find("【") == -1:
			continue
		
		doc = doc.replace("【", "").replace("】","")
		href_dict[url_str % value[0]] = doc
	return render(request, 'milk/index.html', {"urldict":href_dict})
	
	
@login_required
def StasticsReq(request):
	'''【销售统计】'''
	now = MilkCommon.GetStrfTime(MilkCommon.GetNowTime())
	one_day_after = MilkCommon.GetStrfTime(MilkCommon.GetSomeDayAgo(-1))
	
	foodtype = MilkCommon.GetFoodDict()
	foodid_list = sorted(foodtype.keys())
	return render(request, 'milk/stasticsquery.html', {"now": now, "one_day_after": one_day_after, "foodtype": foodtype, "foodid_list" : foodid_list})
	
	
@login_required
def StasticsRes(request):
	'''销售统计结果查询'''
	POST = request.POST
	foodid = int(POST["foodid"])
	start_time = MilkCommon.AsDateTime(POST, name = "start_time")
	end_time = MilkCommon.AsDateTime(POST, name = "end_time")
	
	where_dict = {}
	if foodid:
		where_dict["foodid"] = foodid
	where_dict["start_time"] = start_time
	where_dict["end_time"] = end_time
	
	data_list = MilkCommon.GetStasticsResult(where_dict)
	html = MilkCommon.MakeDataHtml(data_list)
	return HttpResponse("".join(html))
	
	
	
@login_required
def VIPStasticsReq(request):
	'''月卡统计'''
	before = MilkCommon.GetStrfTime(MilkCommon.GetSomeDayAgo(-365))
	now = MilkCommon.GetStrfTime(MilkCommon.GetNowTime())
	
	viptype = MilkCommon.GetVIPInfoDict()
	vipid_list = sorted(viptype.keys())
	
	return render(request, 'milk/vipstasticsquery.html', {"now": now, "before": before, "viptype": viptype, "statype_dict" : MilkCommon.statype_dict})
	
	

def VIPStasticsRes(request):
	'''月卡统计结果查询'''
	POST = request.POST
	print("POST",POST)
	vipindex = POST["vipindex"]
	special = "所有"
	if vipindex.find("special"):
		vipindex = ""
	typeid = int(POST["typeid"])
	start_time = MilkCommon.AsDateTime(POST, name = "start_time")
	end_time = MilkCommon.AsDateTime(POST, name = "end_time")
	
	where_dict = {}
	if vipindex:
		where_dict["vipindex"] = vipindex
	where_dict["statypeid"] = typeid
	where_dict["start_time"] = start_time
	where_dict["end_time"] = end_time
	
	data_list = MilkCommon.GetVIPStasticsResult(where_dict, typeid)
	html = MilkCommon.MakeVIPDataHtml(data_list)
	return HttpResponse("".join(html))
	# return HttpResponse("POST %s" %vipindex)
	
	
	
	

nailezhuang/milk/templates/milk/index.html
<!DOCTYPE html>
<html>
<title>test kg</title>
{% for urlpath, fname in urldict.items %}
<a href="{{ urlpath }}">{{ fname }}</a>
{% endfor %}
</html>

nailezhuang/milk/templates/milk/stasticsquery.html
<!DOCTYPE html>
<html>

<head>
<title>账单统计</title>
<meta charset="UTF-8">
</head>
<body>
<form action="{% url 'milk:StasticsRes' %}" method="post">{% csrf_token %}
<table border='1px' cellspacing='0px' style='border-collapse:collapse'>
<tr><td><label>物品类型</label>
<select name="foodid" style='width:500'>
{% for foodid, foodname in foodtype.items %}
<option value="{{ foodid }} ">{{ foodname }}</option>
{% endfor %}
</select><br>
<tr><td><label>开始时间</label>	<input type='text' name='start_time' value="{{ now }}" style='width:300'/></td></tr>
<tr><td><label>结束时间</label>	<input type='text' name='end_time' value="{{ one_day_after }}" style='width:300'/></td></tr>
</table>
<br>

<input type="submit" value="提交" style="text-align:center;">
</form>
</body>
</html>

nailezhuang/milk/templates/milk/vipstasticsquery.html
<!DOCTYPE html>
<html>

<head>
<title>月卡用户喝奶统计</title>
<meta charset="UTF-8">
</head>
<body>
<form action="{% url 'milk:VIPStasticsRes' %}" method="post">{% csrf_token %}
<table border='1px' cellspacing='0px' style='border-collapse:collapse'>
<tr><td><label>月卡编号</label>
<select name="vipindex" style='width:500'>
{% for vipid, vipindex in viptype.items %}
<option value="{{ vipindex }} ">{{ vipindex }}</option>
{% endfor %}
</select><br>
<tr><td><label>统计类型</label>
<select name="typeid" style='width:500'>
{% for typeid, typename in statype_dict.items %}
<option value="{{ typeid }} ">{{ typename }}</option>
{% endfor %}
</select><br>
<tr><td><label>开始时间</label>	<input type='text' name='start_time' value="{{ before }}" style='width:300'/></td></tr>
<tr><td><label>结束时间</label>	<input type='text' name='end_time' value="{{ now }}" style='width:300'/></td></tr>
</table>
<br>

<input type="submit" value="提交" style="text-align:center;">
</form>
</body>
</html>